def display_cv_info(cv: CVData):
    # Existing content...
    
def display_matches(results: list[MatchResult], limit: int = 20):
    # Existing content...

async def scrape_jobs(countries: list[str], keywords: str, sites: list[str], limit: int) -> list[Job]:
    # Existing content...
